#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "backend"))

from app.geocooling.decision_context_v1 import (  # noqa: E402
    DataQuality,
    DecisionForecast,
    DecisionRisk,
    RiskLevel,
    build_decision_context,
)


def main() -> int:
    context = build_decision_context(
        measurements={
            "indoor_temperature_c": 25.1,
            "indoor_humidity_pct": 54.0,
            "outdoor_temperature_c": 29.4,
            "dew_point_c": 15.2,
        },
        configuration={
            "comfort_target_c": 24.0,
            "cooling_start_threshold_c": 25.0,
            "cooling_stop_threshold_c": 23.8,
            "condensation_margin_c": 4.2,
            "minimum_condensation_margin_c": 3.0,
            "building_inertia": "UNKNOWN",
        },
        availability={
            "weather": True,
            "historian": True,
            "learning": False,
            "prediction": True,
            "hardware": False,
        },
        quality={
            "sensors": DataQuality.GOOD,
            "weather": DataQuality.GOOD,
            "learning": DataQuality.INSUFFICIENT,
            "prediction": DataQuality.DEGRADED,
        },
        forecasts=[
            DecisionForecast(
                horizon_minutes=120,
                indoor_temperature_c=25.7,
                confidence=0.70,
                source="validation",
            )
        ],
        risks=[
            DecisionRisk(
                code="HARDWARE_NOT_CONNECTED",
                level=RiskLevel.MEDIUM,
                message="Passive observation only",
                blocking=False,
            )
        ],
        reasons=[
            "Decision Context contract installed",
            "No hardware command is generated by RC1.7A",
        ],
        recommendation={
            "action": "WAIT",
            "confidence": 0.75,
        },
        metadata={
            "patch": "RC1.7A",
            "mode": "passive",
        },
    )

    payload = context.as_dict()

    output = REPO / "audits" / "rc17a-decision-context"
    output.mkdir(parents=True, exist_ok=True)

    report = output / "sample-context.json"
    report.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print(json.dumps(payload, ensure_ascii=False, indent=2))
    print()
    print("Report:", report)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
