from enum import StrEnum


class GeoCoolingState(StrEnum):
    OFF = "OFF"
    OPENING_VALVE = "OPENING_VALVE"
    WAITING_FLOW = "WAITING_FLOW"
    STARTING_PUMP = "STARTING_PUMP"
    RUNNING = "RUNNING"
    STOPPING_PUMP = "STOPPING_PUMP"
    WAITING_DRAIN = "WAITING_DRAIN"
    CLOSING_VALVE = "CLOSING_VALVE"
    FAULT = "FAULT"
    EMERGENCY_STOP = "EMERGENCY_STOP"


class GeoCoolingMode(StrEnum):
    SIMULATION = "SIMULATION"
    MANUAL = "MANUAL"
    AUTO = "AUTO"
    OFF = "OFF"
